### ISSUE TITLE
loading--dark modifier not working as expected

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#1007]
<img width="327" alt="Screen Shot 2021-04-27 at 11 26 17 PM" src="https://user-images.githubusercontent.com/108094/116356383-0c74dc80-a7b0-11eb-87e3-d1205b0a3003.png">

🤔  See what changed from https://github.com/mapbox/assembly/pull/987

**Comment by samanpwbb** [comment]
We need to redeclare border-top-color:
```css
.loading--dark {
    color: #fff;
    border-color: rgba(255,255,255,.25);
    border-top-color: currentColor;
}
```
