### ISSUE TITLE
assembly.min.css missing `border-top-color` in `.loading--dark`

### ISSUE THREAD

**Issue by katydecorah** [mapbox/assembly#1019]
While reviewing https://github.com/mapbox/mr-ui/pull/124, I noticed that the `loading--dark` appears as a circle without a visible spinner:

> ![image](https://user-images.githubusercontent.com/2180540/119007329-20e76780-b95f-11eb-9d68-8462f02d1d7c.png)

I think this is because the `border-top-color` is not getting set. However, the class looks ok:

https://github.com/mapbox/assembly/blob/18502e43f46da550a9258e2cad44e3bcf2763c43/src/miscellaneous.css#L78-L82

When I run `npm run build` in this repo:

`dist/assembly.css` returns:

```css
.loading--dark {
  color: #fff;
  border-color: rgba(255, 255, 255, 0.25);
  border-top-color: currentColor;
}
```

but `dist/assembly.min.css` returns:

```css
.loading--dark{color:#fff;border-color:rgba(255,255,255,.25)}
```

According to the csso documentation:

> In case of border, margin, padding, font and list-style properties, the following removal rule will be applied: if the last property is a 'general' one (for example, border), then all preceding overridden properties will be removed (for example, border-top-width or border-style).
https://github.com/css/csso/blob/master/docs/description/description.en.md#removal-of-overridden-shorthand-properties

But in this case, we have the 'general' one above. So I'm not sure if this is csso issue or something else.

I tried `border-top-color: currentColor !important;` and the property passed through to the minified CSS, but would prefer to find another solution before implementing important.
