### ISSUE TITLE
Just use `.woff` for @font-face

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#185]
It looks like we can drop the embedded opentype rules from our @font-face rules! This should be all we need:

```css
@font-face {
  font-family: 'WebFont';
  src: url('myfont.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}
```

cc @katydecorah @samanpwbb
