### ISSUE TITLE
What is the purpose of blockquote::after pseudo-elements

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#264]
I ran across this rule and I'm not sure what it's for:

```css
.prose blockquote::before,
.prose blockquote::after,
.prose q::before,
.prose q::after {
  content: '';
}
```

@katydecorah is there a reason I'm missing, or is that a relic of some prior iteration?
