### ISSUE TITLE
prose list margin bottom classes are problematic:

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#266]
These rules don't really work:
```css
.prose > ol,
.prose > ul {
  margin-bottom: 20px;
}
```

This situation is very common (especially in react):

```html
<div class='prose'>
  <div>
    <ul>
    </ul>
  </div>
</div>

```

 @katydecorah is the original intention of this to prevent lists-in-lists from having a bottom margin?
