### ISSUE TITLE
pos- prefix on positioning rules or no?

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#28]
Right now I have positioning rules that look like this:

``` css
/**
 * Positioning utility classes
 * @namespace Positioning
 * @memberof Utilities
*/
.fix { position: fixed; }
.abs { position: absolute; }

/*
Zero out positioning
*/
.top    { top: 0; }
.right  { right: 0; }
.left   { left: 0; }
.bottom { bottom: 0; }
```

so instead of `pin-topright`, you'd write `abs top right`. I think this is nice, but it sorta breaks the rules. `abs pos-top pos-right` would be more aligned with convention.
