### ISSUE TITLE
to what extent should we add media query classes

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#32]
We could potentially duplicate every class across every media query. Where do we draw the line? I'm adding some basic positioning and display classes:

``` css
.inline { display: inline; }
.block { display: block; }
.inline-block { display: inline-block; }
.flex { display: flex; }
.hidden { display: none; }
```

`hidden-sm`, `inline-sm`, `block-sm`, `inline-block-sm` definitely make sense... `flex-sm` less so, but maybe. Do we need to tackle this case-by case? Where do we draw the line?
