### ISSUE TITLE
Can .prose *:last-child rules use a universal selector?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#461]
Can

```css
.prose h1:last-child,
.prose h2:last-child,
.prose h3:last-child,
.prose h4:last-child,
.prose h5:last-child,
.prose h6:last-child,
.prose p:last-child,
.prose pre:last-child,
.prose ol:last-child,
.prose ul:last-child,
.prose ol ol:last-child,
.prose ul ul:last-child,
.prose ol ol ol:last-child,
.prose ul ul ul:last-child,
.prose img:last-child,
.prose video:last-child {
  margin-bottom: 0;
}
```

become

```css
.prose *:last-child { margin-bottom: 0; }
```

??
