### ISSUE TITLE
Aligning curly braces

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#48]
By "aligning curly braces" I mean this:

```css
.bg-blue   { background-color: #0077cc; }
.bg-purple { background-color: #5500cc; }
```

instead of this:

```css
.bg-blue { background-color: #0077cc; }
.bg-purple { background-color: #5500cc; }
```

Here are some disadvantages, I think:

- You have to do it.
- It's easy to mess up but hard to automatically enforce.
- Diffs are less useful when you add a new, longer-named class but end up changing several unrelated lines by one space because of the new positioning (if you remember).
- You have to ask yourself questions about when to align what with what, e.g. after line breaks — instead of not thinking about it at all.

I don't know of any advantages (?).

So, I guess I'm in favor of using an easily-enforceable, no-thought-required convention of putting the curly brace one space after the selector. What do *you* think?
