### ISSUE TITLE
Simplify `.btn--pill-{pos}` modifiers

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#588]
Right now there's [a lot of modifier classes required](https://github.com/mapbox/assembly/blob/95c1135a1ab1215105aacba5a6c652bcde0b91e7/src/buttons.css#L175-L229) to create proper rounded effects for pills. I'd expect `btn--pill` to just work without having to maintain the roundness of it. I might be completely naive here but wouldn't something like:

```css
.btn--pillx { border-radius: 0; }
.btn--pillx:first-child { border-radius: 3px 0 0 3px; }
.btn--pillx:last-child { border-radius: 0 3px 3px 0; }

/* Do the same for vertical rules ... .btn-pilly */
```

Work? I guess the caveat is that it overrides any round modifications added. Could this be the default behaviour for pill components (un `!important` ized).

cc @davidtheclark
