### ISSUE TITLE
Should grid cols be max-width instead of min-width?

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#68]
I'm thinking maybe classes like these:

```css
.col2 { min-width: 16.6666%; }
.col3 { min-width: 25%; }
.col4 { min-width: 33.3333%; }
.col5 { min-width: 41.6666%; }
```

Should be changed to `max-width`. Right now if I put a `.col6` element alone in a row, it fills the whole row.

cc @tristen
