### ISSUE TITLE
`transition` class

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#696]
we have a transition-none class https://github.com/mapbox/assembly/blob/22adf098b31267eda204d156a1a0c857e97b68e7/src/miscellaneous.css#L109-L111

it would make sense to also have a `transition` class that matches buttons and other form element's transition:

```css
.transition {
  transition: all .125s;
}
```
