### ISSUE TITLE
easy way to make flexible, equal width children elements

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#819]
There should be a way in Assembly to make an  equal-width flexible grid with any number of children (if two children, they're both 50% width, if 3 children, they're all 33.333% width, ect). Flexbox makes this easy. We could add a utility:

```css
.flex-child--equal {
  flex-basis: 0;
  flex-grow: 1;
  flex-shrink: 1;
}
```

_Otherwise_, and I think this is the better idea, we could make the `.col` class take on this behavior by default. Thoughts @mapbox/frontend ?
