### ISSUE TITLE
loading classes are too subtle

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#859]
we need loading classes that work against either light or dark backgrounds (for example, we need to be able to display loaders on top of custom maps that could be any color). Using a light and a dark color, one inside the other, or increasing contrast will help. 

cc: @dasulit

**Comment by samanpwbb** [comment]
Here's what I'm using elsewhere:
```css
.loading--dark::after {
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' version='1.1' width='36' height='36' viewBox='0 0 36 36'%3E%3Cdefs%3E%3Cstyle%3E.a%7Bfill:%23fff;%7D.b%7Bopacity:0.5;%7D.c%7Bfill:%23273d56;%7D%3C/style%3E%3C/defs%3E%3Cpath class='a' d='M5.2721,5.2721,7.3934,7.3934a15,15,0,0,1,21.2132,0l2.1213-2.1213A18,18,0,0,0,5.2721,5.2721Z'/%3E%3Cg class='b'%3E%3Cpath class='c' d='M28.6066,28.6066A15,15,0,0,1,7.3934,7.3934L5.2721,5.2721a18,18,0,1,0,25.4558,0L28.6066,7.3934A15,15,0,0,1,28.6066,28.6066Z'/%3E%3C/g%3E%3C/svg%3E");
}
```

i just updated the colors to have more contrast, and this seems to work well on top of a variety of backgrounds.
