### ISSUE TITLE
Cannot override disabled button colors

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/assembly#860]
The rule for disabled buttons looks like this:

```css
.btn:disabled {
  pointer-events: none;
  color: var(--inactive-text-color) !important;
  background-color: var(--disabled-primary-interactive-color) !important;
  box-shadow: none !important;
}
```

I'm not sure why those `!important`s would be necessary. And the effect they're having tonight is to block me from overriding the disabled button's background color with a `bg-*` class.
