### ISSUE TITLE
viewport min/max classes

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/assembly#886]
I have been frequently writing classes like:

```css
.hmax-viewport-half {
  max-height: 50vh;
}
```

And I think a full set of min/max viewport classes would be very useful without adding much bloat.
