### ISSUE TITLE
Build with inverted colors to support dark mode

### ISSUE THREAD

**Issue by tristen** [mapbox/assembly#954]
This might be a nice way of supporting dark mode in Studio: either by automatically supporting an inversion for some color:

```css
.bg-white { background: #FFF; }

@media (prefers-color-scheme: dark) {
  .bg-white { background: #000; }
}
``` 

Or creating additional classes to target what the inversion should be:

```css
@media (prefers-color-scheme: dark) {
  .bg-white--dark-mode { background: #FFF; }
}
```
